### ISSUE TITLE
LoopScrollRect里的回放语音按钮会消失

### ISSUE THREAD

**Issue by gyf1214** [Lunatic-Works/Nova#23]
#16 目前不太清楚什么情况下会发生，但是比较频繁

**Comment by gyf1214** [comment]
还有一个问题是如果滚动条拉到最上面然后再滚轮往下会直接关闭Log窗口

**Comment by woct0rdho** [comment]
我觉得`LogController`里应该不需要把`LogParam`和`LogEntry`分成两个东西，我看看吧。。

（我们正在改的是`new_save2` branch）

**Comment by gyf1214** [comment]
master也会有这个问题

**Comment by qiankanglai** [comment]
这个问题这两天晚上有空了我也跟进下

**Comment by woct0rdho** [comment]
滚轮的问题修了一下，看 #24 吧

**Comment by woct0rdho** [comment]
草，按钮消失的问题也修好了，看 https://github.com/Lunatic-Works/Nova/commit/12c6aa84c0634bb6651eebd5b4c9c05496606806

**Comment by woct0rdho** [comment]
`new_save2` branch上我修了一下

`ReachedDialogueData`记录的是跟`FlowChartTree`有关的东西，在每条对话的default代码块运行之前生成，而voices是在default代码块运行中生成的，所以voices不能放在`ReachedDialogueData`里，我在`DialogueChangedData`里单独加了voices

`LogController` restore时，也不能从`FlowChartTree`里读取voices，必须把voices存到checkpoint里，所以我在`LogEntryRestoreData`里加了voices

这样一来，`LogEntryRestoreData`就没有原来那么稀疏了，我觉得还是要把所有`LogEntryRestoreData`分开存到所有checkpoint里。Restore n个log entry的时间至少是O(n)，就算你把所有`LogEntryRestoreData`存到一个checkpoint里，restore的时间也是O(n)。如果发现deserialize很多个checkpoint的速度太慢，到时候再想办法。。

另外，我们也许可以把voices放到`FlowChartTree`里，但是这就需要在parse脚本的时候运行所有控制auto voice的Lua代码，或者用其他语法来控制auto voice。。

**Comment by gyf1214** [comment]
还是可以把voices放到ReachedDialogueData里的，只要把SetReached放到default action之后就行了，见6f37dd13a3bfe1d3495035ee099ec3a2bf4f0c50

**Comment by gyf1214** [comment]
Solved
