### ISSUE TITLE
希望文档补充Quick Start

### ISSUE THREAD

**Issue by youngstudent2** [Lunatic-Works/Nova#30]
hi~ 最近在学习使用Nova，我在新增ch5.txt后将ch1末尾改为`@<| jump_to 'ch5' |>`，发现在章节选取页面只有第一章到第三章的索引，第四章和第五章丢失了；另一方面注意到Tools下有不少工具但wiki中似乎没介绍到

想了解下Nova开发时的工作流程是怎样的，比如新增章节、新增动画等等

谢谢~

**Comment by woct0rdho** [comment]
一章开头的`@<| ... |>`里加了`is_start`才会出现在章节选择界面里，具体可以在[wiki](https://github.com/Lunatic-Works/Nova/wiki/NovaScript)里搜`is_start`看看

Tools下面的很多东西都还不稳定，我们以后可能还会改，所以目前没写文档

我们的确得先看看别人需要什么，才知道该怎么写文档，你可以先问一些具体的问题

**Comment by youngstudent2** [comment]
is_start与章节选择的对应关系在`tut02.txt`中提到了，但在wiki-NovaScript一节中没提到，希望补充 🌹 

感谢解答，后续学习中应该还会遇到具体问题
