### ISSUE TITLE
demo项目build&run失败了

### ISSUE THREAD

**Issue by beerchyan** [Lunatic-Works/Nova#4]
在调试环境下可以跑起来正常运行，但是打成exe以后进入游戏出现unity标志后就闪退了
unity版本： 2020.3.5f1c1 (548653c6c3de)

**Comment by woct0rdho** [comment]
你在build之前做过这些了吗？https://github.com/Lunatic-Works/Nova/wiki/Build

Player log里有报错吗？（Player log的位置是`%USERPROFILE%\AppData\LocalLow\CompanyName\ProductName\Player.log`）

**Comment by beerchyan** [comment]
对不起大佬我没有去看文档。。我这就去研究一下

**Comment by beerchyan** [comment]
可以了，谢谢大佬！公司破网总连不上github抓紧时间回一个消息谢谢大佬
