### ISSUE TITLE
关于接入Live2D SDK

### ISSUE THREAD

**Issue by rin-miku** [Lunatic-Works/Nova#43]
Nova/Sources 文件夹下的脚本无法引用Live2D的命名空间，如果想接入Live2D的话有其他什么办法吗

**Comment by rin-miku** [comment]
解决方案 导入Live2D后 手动移动到 Nova/Sources 文件夹下某一位置即可

**Comment by woct0rdho** [comment]
我们在`Assets/Nova/Sources/`下面放了一个Nova.asmdef，这样可以把Nova的代码单独编译成一个DLL

如果你要在C#中调用Live2D的代码，并且Live2D SDK里面有asmdef，只要在Nova.asmdef里面引用他们的asmdef就行了

如果他们没有asmdef，那就只能把Live2D的代码移动到`Assets/Nova/Sources/`下面，像目前的ToLua#一样

但是如果你要把Live2D绑定到Lua，目前Lua绑定只支持namespace Nova下面的东西，等我们有空会想办法支持外面的东西，需要对ToLua#生成代码的部分做一些修改

**Comment by rin-miku** [comment]
Live2D SDK中无程序集定义文件，因此暂时还是采取移动代码到指定文件夹下的方法，感谢您的回复
