### ISSUE TITLE
nova有预留视频流的接口吗？galgame有放oped的需求来着

### ISSUE THREAD

**Issue by DDDPG** [Lunatic-Works/Nova#47]

**Comment by DDDPG** [comment]
收到，以及如果想要实现bgm的淡入淡出应该在lua哪里下手呢，是play函数那里吗？

**Comment by woct0rdho** [comment]
可以用`anim:fade_in`和`fade_out`，这里有文档 https://github.com/Lunatic-Works/Nova/wiki/NovaScript#%E5%A3%B0%E9%9F%B3-audiolua

我突然发现教程里没有讲这个，等我有空加一下。。
