### ISSUE TITLE
Tutorial04 播放到警告弹出框后无法继续

### ISSUE THREAD

**Issue by YuzhouGuo** [Lunatic-Works/Nova#49]
对照着txt，播放到[这一句](https://github.com/YuzhouGuo/Nova/blob/7ca99379d152147240db7fa73f392c51fca68b3f/Assets/Resources/Scenarios/tut04.txt#L132)后就无法继续了，关闭了警告弹出框后，鼠标左键没有任何效果。

系统：MacOS 10.15.6
Unity版本：2021.3.14f1
clone from master后没有人工修改version，直接让unity完成的版本升级，然后打开main scene播放至此

是我哪里操作不对吗，感谢。

**Comment by woct0rdho** [comment]
你可以先用v0.3 branch，v0.4目前来看问题挺多的，我们估计下个星期会修一下

**Comment by woct0rdho** [comment]
修了一下，现在可以再试试

**Comment by YuzhouGuo** [comment]
好的感谢
