### ISSUE TITLE
DialogueEntry中更改“name”选项的color之后，游戏内的角色人物名对应颜色没有更改仍然为黑色

### ISSUE THREAD

**Issue by DDDPG** [Lunatic-Works/Nova#50]
![C3B9A50CD2F0FFDFCC46564728EE3D5D](https://user-images.githubusercontent.com/98150722/224549787-8d620c33-28e6-499b-b851-24de32afb6a8.jpg)

**Comment by woct0rdho** [comment]
`DialogueEntry`里的姓名和对话的颜色都是在`DialogueBoxController.Append`里初始化`DialogueEntry`的时候设置的

如果你要让姓名和对话有不同的颜色，可以改那里的代码
