### ISSUE TITLE
Unity 2023 `cameraColorTargetHandle`的问题

### ISSUE THREAD

**Issue by bluuueheart** [Lunatic-Works/Nova#65]
报错 刚才的一些我解决了，也是pakage里面的一点问题
<img width="978" alt="image" src="https://github.com/Lunatic-Works/Nova/assets/147491428/6dbf9a99-8d25-4f42-bdf9-21686ffada21">

**Comment by woct0rdho** [comment]
这个问题你按照报错的内容来改就行了

我刚才修了一下，可以按照这个commit来改：
https://github.com/Lunatic-Works/Nova/commit/3c0d691881a46d2bdb7fefaaf821042e12e81179

还不行的话重新下载最新版的Nova应该就行了

**Comment by bluuueheart** [comment]
我换回2021版本，可以运行了，谢谢！
