### ISSUE TITLE
脚本相关报错问题

### ISSUE THREAD

**Issue by bluuueheart** [Lunatic-Works/Nova#66]
![image](https://github.com/Lunatic-Works/Nova/assets/147491428/9be46359-9cc3-4e0e-8fc7-5ca99e34a073)
请问怎么解决呢，感谢！

**Comment by woct0rdho** [comment]
最上面一个报错是`ParserException`，意思就是你的脚本格式有问题。你的脚本是怎么写的，发上来看看吧

**Comment by bluuueheart** [comment]
谢谢！修改了脚本，现在变成了这样
![image](https://github.com/Lunatic-Works/Nova/assets/147491428/43af1ca6-9258-45ad-b77f-4b25c6a57b4c)

**Comment by woct0rdho** [comment]
`LuaException`说明你的脚本里NovaScript（就是`<| ... |>`）之类的格式没错，但是Lua代码的语法错了

另外，你在发报错信息的时候，可以先选中Console窗口上半部分的一个报错，下半部分会显示更详细的报错信息，把它也发上来

如果你不知道怎么改的话，可以把这段脚本发上来看看

**Comment by bluuueheart** [comment]
![image](https://github.com/Lunatic-Works/Nova/assets/147491428/5ab742a3-b128-4a75-9635-476e017d39bc)
我修改了脚本，发现之前是中文`，`的问题。

**Comment by bluuueheart** [comment]
修改node之后脚本可以正常运行！现在的报错如下，请问是和背景图无法正常显示有关吗？感谢您的耐心！
![image](https://github.com/Lunatic-Works/Nova/assets/147491428/7d790d1e-6d5f-466c-99a6-eed3d8b27453)

**Comment by woct0rdho** [comment]
这个应该是`show`的第一个参数你写了一个不存在的东西

**Comment by bluuueheart** [comment]
写的是`show(角色, 'normal')`。检查了创建角色：Standings里有对应文件夹，Inspector修改了，pose也定义了，但是还是有这个报错。

**Comment by woct0rdho** [comment]
啊我刚才看错了，这个报错是`attemp to index local 'obj' (a number value)`，说明Lua把它当成了数字，可能是因为Lua里的变量不能以数字开头

如果报错是`a nil value`，才说明它是不存在的东西

还不行的话，你把脚本发上来看看吧

**Comment by bluuueheart** [comment]
已经解决了~是数字开头的问题，现在脚本应该没有其他问题了，感谢您的帮助！
