### ISSUE TITLE
关于Branch中嵌入Branch的问题

### ISSUE THREAD

**Issue by bluuueheart** [Lunatic-Works/Nova#67]
请问如果我尝试在Branch中嵌入Branch，即脚本中会出现形如
```
@<| label 'm_end_choice' |>
@<| jump_to 'l_end_choice' |>
@<| label 'l_end_choice' |>
```
的情况，是行得通的吗？我尝试后出现了如图报错：
![image](https://github.com/Lunatic-Works/Nova/assets/147491428/936d3568-a841-4790-9c6e-19d1fc268e59)

**Comment by woct0rdho** [comment]
每个node的开头和结尾必须各有一个eager execution block（就是`@<| ... |>`，没有`@`的代码块我们叫做lazy execution block）。开头的`@<| ... |>`里面必须有`label`，结尾的`@<| ... |>`里面必须有`jump_to/branch/is_end`

你的
```
@<| label 'm_end_choice' |>
@<| jump_to 'l_end_choice' |>
```
构成一个node，而下面的
```
@<| label 'l_end_choice' |>
```
的结尾没有`@<| ... |>`，所以会有警告

**Comment by bluuueheart** [comment]
解决了，辛苦了
