### ISSUE TITLE
关于字体的问题

### ISSUE THREAD

**Issue by lyranh** [Lunatic-Works/Nova#69]
请问生成了font asset并且创建了新的material后，又怎么设置更换字体呢？

**Comment by woct0rdho** [comment]
可以按照这个教程走一遍： https://github.com/Lunatic-Works/Nova/wiki/Font-Asset#%E6%9B%B4%E6%8D%A2font-asset

先在`I18nFontConfig`里设置语言、font asset、material的名字和material asset，再在`dialogue_box.lua`里把material的名字和对话框的style绑定，最后在脚本里用`set_box`设置对话框的style

（我也觉得这个过程比较麻烦，但是这一切主要是为了支持多语言）
