### ISSUE TITLE
了解Nova时遇到的一些问题

### ISSUE THREAD

**Issue by qiankanglai** [Lunatic-Works/Nova#7]
Hi 最近<del>摸鱼</del>时候了解了下Nova 可能想用来和朋友一起移植一款AVG。看代码过程中遇到了一些问题or建议 希望能一起讨论下

- 使用说明中需要把几个文件夹从`Example/Colorless`里挪出，我试了下最新版本其实可以直接跑（而且我看了下目前master分支用的是Resources这个机制，确实子文件夹是可以直接获取的）从上手角度来说，能做到开箱即用肯定更加舒服
- 立绘利用了SpriteMerge机制，但是其实本身AVG类的相对不会draw call bound（特别是PC就更加不敏感了），如果考虑手机版的话其实从硬件压缩格式->uncompressed RT反而亏了，有点吃不准这个机制的出发点orz

> 绝大多数Unity能做的gameplay都可以加到Nova里

关于这个其实是我目前比较头疼的地方，譬如希望加入一些特殊玩法的话，和Nova本身如何结合比较合适？例如某个chapter需要打俄罗斯方块，这时候Nova本体部分如何暂停、游戏完成后如何交互更新一些状态信息等？

**Comment by woct0rdho** [comment]
以前我们打算把Colorless就当作一个示例，然后在菜单里做一个按钮来新建一个Nova模板，后来就鸽了。。。既然终于有人吐槽了，那我就把文件夹移一下吧，现在已经移好了。

关于立绘，我们需要解决一个问题：比如人物的脸和眼睛分成两个图层，而人物消失的时候有一段变透明的动画，那么需要先把脸和眼睛blend成一张图，再设成半透明，再blend到背景上。否则，如果先把半透明的脸blend到背景上，再把半透明的眼睛blend上去，看起来就是眼睛消失得比较慢，或者说露出本来被眼睛挡住的那一部分脸。

我们确实不需要太在意draw call，所以理论上在把所有图层blend成一张图的时候不用开一个很大的RT，但是需要改渲染流程，我们的下一个大版本里可能会改，如果你有兴趣的话可以帮我们写这个OvO

关于小游戏，我得写个教程。。。但是教程又不知不觉鸽了一个月。。。这个圣诞假期我肯肯肯肯肯定写。大概的思路是：

* 进入小游戏
    1. 在`小游戏Controller` class里写一个`Show`函数，用来显示小游戏的UI
    2. 在class上面加上`[ExportCustomType]` attribute，用来导出Lua接口
    3. 在class文件里加上`using LuaInterface;`，在`Awake`函数里加上`LuaRuntime.Instance.BindObject("小游戏名字", this);`，就会把小游戏的C# object instance绑定到Lua的`__Nova`这个全局table里的`小游戏名字`这个key
        * 如果小游戏有好几个instance，可以把`小游戏名字`改成一个变量
    3. 在Unity Editor的上面的菜单中点击`Lua -> Clear Wrap Files`，就会生成这个class的Lua接口
    4. 在Lua脚本里写`__Nova.小游戏名字:Show()`，就会显示小游戏的UI
* 在小游戏中禁止用户对Nova本体的操作
    1. 用小游戏的UI挡住`DialogueView`，就会禁用点击
        * 如果挡不住，可以在小游戏的后面加一个透明的panel，或者直接用`NonDrawingGraphic`
    2. 在Lua脚本里写`input_off()`，就会禁用快捷键
        * 其实是调用`GameController.DisableInput`
    3. 退出小游戏之后，在下一条文本的Lua脚本里写`input_on()`，就会启用快捷键
    4. 如果用户点右上角的叉退出游戏，会出现“是否退出游戏”的警告框，所以要让`Alert`显示在小游戏的UI的上面
* 小游戏与Nova本体的信息传递
    1. 在`小游戏Controller` class的`Awake`函数里，获取变量的引用：
    ```csharp
    gameController = Utils.FindNovaGameController();
    variables = gameController.GameState.variables;
    checkpointHelper = gameController.CheckpointHelper;
    ```
    2. 在进入小游戏之后，用`variables.Get`和`variables.Set`读写变量，`checkpointHelper.GetGlobalVariable`和`checkpointHelper.SetGlobalVariable`读写全局变量
    3. 退出小游戏之后，设置剧情选项，根据变量跳转

**Comment by woct0rdho** [comment]
卧槽你就是`LoopScrollRect`的作者啊，我们以前打算把log界面改成`LoopScrollRect`，你有兴趣的话也可以来帮忙OvO

**Comment by qiankanglai** [comment]
啊哈哈哈没问题啊，等我再熟悉下框架 整个pull request
昨天刚混进QQ群里orz

**Comment by woct0rdho** [comment]
我觉得QQ群里搜索以前的消息比较麻烦（虽然GitHub搜索中文也比较麻烦，但是以后有可能会好起来），如果你觉得你的问题会帮助到更多人，那就在issue里问好了。

> 不过似乎可以考虑额外暴露一个全局的立绘Alpha参数？

你说的“全局”是什么？`CharacterController`已经有`color`和`environmentColor`这两个参数了，而改变颜色和改变alpha的逻辑是一样的，所以我们没打算单独设一个alpha参数。

（有两个颜色参数是因为`color`一般是做变透明或者闪烁之类的短时间的动画用的，而`environmentColor`是做黄昏之类的长时间的颜色变化用的。）

**Comment by qiankanglai** [comment]
早上可能没表达清楚，其实立绘这个需求（不同部件之间类似不透明处理，这样fade out的时候不穿帮）可以考虑用stencil做，效果应该和利用RT是一样的~ 等我有空了拉个分支做个版本试试

**Comment by woct0rdho** [comment]
现在小游戏的功能应该是做完了，可以看看现在的文档 https://github.com/Lunatic-Works/Nova/wiki/Minigame
