### ISSUE TITLE
调用小游戏后，unity显示多个eventsystem同时进行

### ISSUE THREAD

**Issue by Oyemiaomiao** [Lunatic-Works/Nova#70]
请问调用小游戏后，unity显示多个eventsystem同时进行该如何解决
![屏幕截图 2024-04-22 153954](https://github.com/Lunatic-Works/Nova/assets/145257282/f67520f9-9741-435d-aa82-8d139efc0727)
![屏幕截图 2024-04-22 154229](https://github.com/Lunatic-Works/Nova/assets/145257282/4c9ca8f5-ac9e-44ba-8f0b-a1c50acdf548)

**Comment by woct0rdho** [comment]
你看看这个prefab里面的任何game object上面有没有`EventSystem`这个component，按理来说一个游戏里只能有一个`EventSystem`

**Comment by Oyemiaomiao** [comment]
嗯嗯，我把多余的eventsystem删除后确实没有相同的警告了，但小游戏任然无法调用，而且不显示任何的报错和输出，同时对话也卡住了。请问调用小游戏是不是用上图中的代码就可以了，还是还有什么另外的要求吗？

**Comment by woct0rdho** [comment]
你先看看gougu.prefab有没有被加载到Hierarchy里，按理来说它应该被加载到UI里的UIPrefabLoader下面

再看看它有没有显示在画面里

**Comment by Oyemiaomiao** [comment]
没有加载到UIPrefabLoader下面，而出现了报错
![image](https://github.com/Lunatic-Works/Nova/assets/145257282/7982ce95-bad6-4057-abb4-9fd6ecbecbb3)

**Comment by woct0rdho** [comment]
从这个报错来看，报错不是出在你写的脚本里的`minigame`这个地方

你先试试写一段尽量简单的脚本用来测试，比如一个node里只有一条对话，这条对话里只有`minigame`，然后把这段脚本全部发上来

另外，下次截图的时候，选中Console窗口上半部分的一条报错，下半部分会有更详细的报错信息，把那些也发上来

**Comment by Oyemiaomiao** [comment]
重装了一次框架，报错消失了，同时gougu.prefab被加载了到Hierarchy，控制台也没有任何消息，但小游戏完全不显示。卡在原本的对话框。我是使用的您的范例来进行测试的，您能看看有什么问题吗？然后预制件本身是不是也要挂载什么特定脚本，我是在其他项目中写了小游戏，导入到框架所在的项目中，然后删除了eventsystem，再制成预制件。小游戏的场景可以在框架的工程项目中单独运行。
![image](https://github.com/Lunatic-Works/Nova/assets/145257282/05c5b4fd-9fb4-4d96-8a80-4a41504cbf99)

**Comment by woct0rdho** [comment]
你的gougu.prefab原来是放在UI里的吗，还是放在3D空间里的

Unity里放在UI里的东西和放在3D空间里的东西有一些区别，比如放在UI里的东西上面有RectTransform而不是普通的Transform，摄像机/物理用的Layer也会设成UI

如果是放在3D空间里的，就要把__Nova.uiPrefabLoader改成Nova.prefabLoader

**Comment by Oyemiaomiao** [comment]
好了，解决了，谢谢
