### ISSUE TITLE
macOS在编辑器中直接运行Main场景时报错DllNotFoundException: tolua

### ISSUE THREAD

**Issue by Aghenim** [Lunatic-Works/Nova#73]
设备：MacBook Pro 14 (M1 Pro)
复现步骤：
1. git clone项目
2. 修改`ProjectSettings/ProjectVersion.txt`处的版本号到`2021.3.38f1`
3. 在Unity编辑器中打开
4. 遇到一组编译报错，在package manager中升级URP版本后报错消失（10.10.1 -> 12.1.15）
5. 打开`Assets/Scenes`中的Main场景时报错如下：
```
DllNotFoundException: tolua assembly:<unknown assembly> type:<unknown type> member:(null)
LuaInterface.LuaStatePtr.LuaNewState () (at Assets/Nova/Sources/ThirdParty/ToLua/ToLua/Core/LuaStatePtr.cs:78)
LuaInterface.LuaState..ctor () (at Assets/Nova/Sources/ThirdParty/ToLua/ToLua/Core/LuaState.cs:109)
Nova.LuaRuntime.Init () (at Assets/Nova/Sources/Core/LuaRuntime.cs:26)
Nova.LuaRuntime.get_Instance () (at Assets/Nova/Sources/Core/LuaRuntime.cs:181)
Nova.GameState.Awake () (at Assets/Nova/Sources/Core/GameState.cs:31)
UnityEngine.Object:Instantiate(GameObject)
Nova.NovaCreator:Awake() (at Assets/Nova/Sources/Scripts/NovaCreator.cs:25)
```

**Comment by Aghenim** [comment]
补充：
可以成功构建出apple silicon版本的Mac应用
<img width="600" alt="image" src="https://github.com/Lunatic-Works/Nova/assets/35476773/31b9ad04-0783-4a06-be3f-11aa0aa65895">
应用可以正常运行
<img width="600" alt="image" src="https://github.com/Lunatic-Works/Nova/assets/35476773/d7a1c3cd-3851-40c7-93f6-a5270154e98c">
只在编辑器运行场景时报错
<img width="600" alt="image" src="https://github.com/Lunatic-Works/Nova/assets/35476773/0486fba0-c53e-4067-b391-1c6fa460901c">

**Comment by woct0rdho** [comment]
https://github.com/Lunatic-Works/Nova/commit/1a352c9511b2684d3af89fcef186845f91db5391

修了一下，你试试行不行

**Comment by Aghenim** [comment]
可以了，感谢感谢🙏
